version: 2
jobs:
  build:
    working_directory: ~/maxemail_gem
    docker:
      - image: circleci/ruby:2.5.1-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - rails-maxemail-gem-bundle-v2-{{ checksum "Gemfile" }}
            - rails-maxemail-gem-bundle-v2-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: rails-maxemail-gem-bundle-v2-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      # run tests!
      - run:
          name: run tests
          command: bundle exec rspec
      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
workflows:
  version: 2
  build_rails_and_test:
    jobs:
      - build
